const express = require('express');
const router = express.Router();
const { registerDonor, loginDonor, logoutDonor, getDonorDashboard } = require('../controllers/AuthController');
const authMiddleware = require('../middlewares/auth.middlewares');
const Donor = require('../models/Donor');
router.post('/register/donor', registerDonor);
router.post('/login/donor', loginDonor);
router.get('/logout/donor', logoutDonor);
router.get('/donor/dashboard', authMiddleware(Donor));
module.exports = router;